---
title: "Guided Exercise 9 - Classification"
author: "Gloria Grace"
output: pdf_document
geometry: margin=.5in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
library(tidyverse)
theme_set(theme_bw())
```

## Setup

Construct the set of people, some who will repay and others who will not.

```{r}
set.seed(0)
make_group_rand <- function(n, mean, sd, ...) {
  tibble(score = rnorm(n, mean = mean, sd = sd), ...)
}

# "Deterministic normal": we expect n * pnorm(x, mu, sd) of n points to be below x.
make_group <- function(n, mean, sd, ...) {
  tibble(score = 0:100) %>% 
    mutate(n = floor(n * pnorm(score, mean, sd))) %>% 
    mutate(delta = c(diff(n), 0)) %>% 
    uncount(delta) %>% 
    select(score) %>% 
    mutate(...)
}

people <- bind_rows(
  make_group(150, 60, 10, repay = TRUE),
  make_group(150, 40, 10, repay = FALSE)
)
```

Make a dotplot of the people.

```{r}
ggplot(people, aes(x = score, fill = repay)) +
  geom_dotplot(binwidth = 5, dotsize = .5,
               binpositions = "all", method = "histodot", stackgroups = TRUE)
```

<!-- Add headers and chunks for exercises below. -->

```{r}
people %>% 
  summarize(num_repayed = sum(repay),
            frac_repayed = mean(repay))
```


## Exercise 1

```{r}
decisions <- people %>% 
  mutate(granted = score <)
```

## Exercise 2

## Exercise 3

## Exercise 4

## Exercise 5
